app:
  name: "crypto Mainframe"
  domain: "cmfexchange.co.uk"
ssl:
  enabled: true
  email: "support@cryptomainframe.co.uk"
vendor:
  frontend: "git@github.com:rubykube/mikroapp.git"
  tower: "git@github.com:openware/tower.git"
