app:
  name: "Mikro"
  domain: "app.local"
ssl:
  enabled: true
  email: "support@example.com"
vendor:
  frontend:
    repo: "git@github.com:openware/cryptobase.git"
    branch: "master"
  tower: "git@github.com:openware/tower.git"
