version: '3.6'

services:
  peatio:
    image: rubykube/peatio:2.0.0.alpha
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
        #  - ranger
      # - geth
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
    labels: {}
      # traefik.enable: true
      #      traefik.frontend.rule: 'Host: peatio.wb.local'
      # traefik.port: 8000
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  auth:
    image: quay.io/openware/authz-dummy:0.1.1
    environment:
      DUMMY_USER_EMAIL: "admin@barong.io"
      DUMMY_USER_UID: "U123456789"
      DUMMY_USER_ROLE: "admin"
      DUMMY_USER_LEVEL: 3
      DUMMY_USER_STATE: "active"
      DUMMY_JWT_PRIVKEY_FILE: "/secrets/barong.key"
    volumes:
      - ../config/keys:/secrets:ro

  barong:
    image: quay.io/openware/barong2
    env_file:
      - ../config/barong.env
    ports:
      - "8001:8001"
    volumes:
      - ../config/keys:/secrets:ro

  mikroapp:
    image: node:11
    volumes:
      - ../../mikroapp:/home/node
    command:
      - sh
      - -c
      - |
        cd /home/node
        yarn start
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local'
      traefik.port: 3000
