version: '3.6'

services:
  frontend:
    image: node:11
    volumes:
      - ../vendor/frontend:/home/node
    expose:
      - '4200'
    command:
      - sh
      - -c
      - |
        cd /home/node
        yarn exec -- ng serve --host 0.0.0.0 --disable-host-check
    labels:
      traefik.enable: true
      traefik.frontend.priority: 20
      traefik.frontend.rule: 'Host: www.wb.local'
      traefik.port: 4200
  control-tower:
    image: node:11
    volumes:
      - ../vendor/control-panel:/home/node
    command:
      - sh
      - -c
      - |
        cd /home/node
        yarn start
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: admin.wb.local'
      traefik.port: 3000
