version: '3.6'

services:
  gateway:
    image: quay.io/datawire/ambassador:0.40.0
    depends_on:
      - barong
    volumes:
      - ../config/gateway:/ambassador/ambassador-config/:ro
    ports:
      - '8081:80'
      - '8877:8877'
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.${APP_DOMAIN}, peatio.${APP_DOMAIN}, barong.${APP_DOMAIN}; PathPrefix: /api/'
      traefik.frontend.priority: 80
      traefik.port: 80
